### ISSUE TITLE
Questions about the experiment design 

### ISSUE THREAD

**Issue by nikipi** [princetonvisualai/HIVE#1]
Hey,

Interesting work! 

I have a question about the experiment design. For the human evaluation, the 4 different heat map that showed in distinction task is artifical or generated by read methods. As in the paper, I guess you intentionally chose a case for which different methods highlight very different place, but in practice, I think there is some consistency between different methods. Another question can be asked is whether for different tasks(different model trained on different data), whether a same explanation method will result in different evaluation result.

Thanks

**Comment by sunniesuhyoung** [comment]
Hello, I'll try to clarify as many aspects in this reply!

Q. Are the 4 heatmaps shown in Fig. 2 bottom (distinction task) generated by a real explanation method?
A. Yes, they are real GradCAM explanations for the shown input image.

Q. Did we intentionally choose an example where the 4 heatmaps look different?
A. No. 

Q. Can heatmaps explanations for different classes look similar to each other?
A. Yes, and it is a known issue. See https://arxiv.org/abs/1810.03292 for an investigation of heatmap explanations' sensitivity, similarity, etc.

Q. Will our experimental results be same or different in a different experimental setup (e.g., model, data)?
A. I don't know and would love to find out. If you end up using our evaluation tasks to evaluate different interpretability methods in a different experimental setup, please let us know what happens :)
